// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AResult: typeof import('ant-design-vue/es')['Result']
    ATable: typeof import('ant-design-vue/es')['Table']
    BasicRouter: typeof import('./src/pages/BasicRouter.vue')['default']
    BasicVuex: typeof import('./src/pages/BasicVuex.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    DataShowcase: typeof import('./src/pages/DataShowcase.vue')['default']
    DepList: typeof import('./src/components/DepList.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Requirements: typeof import('./src/pages/Requirements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
    SubComponent: typeof import('./src/components/SubComponent.vue')['default']
    VueBasic: typeof import('./src/pages/VueBasic.vue')['default']
  }
}
